version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    volumes:
      - "/opt/mongodb/data:/data/db"
      - "/opt/mongodb/backups:/data/backups"
      - "/opt/mongodb/exports:/data/exports"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: vanePass
    ports:
      - "27017:27017"
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
